version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/valyala/fasthttp
    versions:
    - 1.22.0
    - 1.23.0
